# Generated by Django 4.2.26 on 2025-12-01 16:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_atleta', models.CharField(max_length=100)),
                ('apellido_atleta', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('sexo', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_sangre', models.CharField(blank=True, max_length=10, null=True)),
                ('datos_representante', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono_representante', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Atleta',
                'verbose_name_plural': 'Atletas',
                'db_table': 'atleta',
            },
        ),
        migrations.CreateModel(
            name='GrupoAtleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rango_edad_minima', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('rango_edad_maxima', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('categoria', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Grupo de Atleta',
                'verbose_name_plural': 'Grupos de Atletas',
                'db_table': 'grupo_atleta',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('clave', models.CharField(max_length=255)),
                ('foto_perfil', models.CharField(blank=True, max_length=255, null=True)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('rol', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='PruebaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('tipo_prueba', models.CharField(choices=[('RESISTENCIA', 'Resistencia'), ('VELOCIDAD', 'Velocidad'), ('FUERZA', 'Fuerza'), ('FLEXIBILIDAD', 'Flexibilidad'), ('AGILIDAD', 'Agilidad'), ('COORDINACION', 'Coordinación')], max_length=20)),
                ('resultado', models.FloatField()),
                ('unidad_medida', models.CharField(max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas_fisicas', to='basketball.atleta')),
            ],
            options={
                'verbose_name': 'Prueba Física',
                'verbose_name_plural': 'Pruebas Físicas',
                'db_table': 'prueba_fisica',
            },
        ),
        migrations.CreateModel(
            name='PruebaAntropometrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('indice_masa_corporal', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('estatura', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('altura_sentado', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('envergadura', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('indice_cornico', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('peso', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas_antropometricas', to='basketball.atleta')),
            ],
            options={
                'verbose_name': 'Prueba Antropométrica',
                'verbose_name_plural': 'Pruebas Antropométricas',
                'db_table': 'prueba_antropometrica',
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField()),
                ('tipo_inscripcion', models.CharField(choices=[('NUEVO', 'Nuevo'), ('RENOVACION', 'Renovación'), ('TRANSFERENCIA', 'Transferencia')], default='NUEVO', max_length=20)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('habilitada', models.BooleanField(default=False)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='basketball.atleta')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'db_table': 'inscripcion',
            },
        ),
        migrations.CreateModel(
            name='EstudianteVinculacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(max_length=100)),
                ('semestre', models.CharField(max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante_vinculacion', to='basketball.usuario')),
            ],
            options={
                'verbose_name': 'Estudiante de Vinculación',
                'verbose_name_plural': 'Estudiantes de Vinculación',
                'db_table': 'estudiante_vinculacion',
            },
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=100)),
                ('club_asignado', models.CharField(max_length=100)),
                ('grupos', models.ManyToManyField(blank=True, related_name='entrenadores', to='basketball.grupoatleta')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrenador', to='basketball.usuario')),
            ],
            options={
                'verbose_name': 'Entrenador',
                'verbose_name_plural': 'Entrenadores',
                'db_table': 'entrenador',
            },
        ),
        migrations.AddField(
            model_name='atleta',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atletas', to='basketball.grupoatleta'),
        ),
    ]
